paul_maxwell_blog_homepage:
    pattern:  /
    defaults: { _controller: PaulMaxwellBlogBundle:Default:index }

paul_maxwell_blog_article:
    pattern:  /article/{id}
    defaults: { _controller: PaulMaxwellBlogBundle:Default:showArticle }
    requirements:
        id: "^[0-9]+$"

paul_maxwell_blog_category:
    pattern:  /category/{id}
    defaults: { _controller: PaulMaxwellBlogBundle:Default:showCategory }
    requirements:
            id: "^[0-9]+$"
