paul_maxwell_blog_homepage:
    pattern:  /
    defaults: { _controller: paul_maxwell_blog_bundle.controller.default:indexAction }

paul_maxwell_blog_article:
    pattern:  /article/{id}
    defaults: { _controller: paul_maxwell_blog_bundle.controller.default:showArticleAction }
    requirements:
        id: "^[0-9]+$"

paul_maxwell_blog_category:
    pattern:  /category/{category_id}
    defaults: { _controller: paul_maxwell_blog_bundle.controller.default:indexAction }
    requirements:
        category_id: "^[0-9]+$"

paul_maxwell_blog_tag:
    pattern:  /tag/{tag_id}
    defaults: { _controller: paul_maxwell_blog_bundle.controller.default:indexAction }
    requirements:
        tag_id: "^[0-9]+$"

paul_maxwell_blog_aboutme:
    pattern:  /aboutme
    defaults:
        _controller: paul_maxwell_blog_bundle.controller.static_page:indexAction
        page: about_me
