paul_maxwell_blog:
    resource: "@PaulMaxwellBlogBundle/Resources/config/routing.yml"
    prefix:   /

paul_maxwell_guestbook:
    resource: "@PaulMaxwellGuestbookBundle/Resources/config/routing.yml"
    prefix:   /guestbook

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
