security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts|bundles)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                csrf_provider: form.csrf_provider
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: paul_maxwell_blog_homepage

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
