security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: 'admin', roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts|bundles)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: paul_maxwell_blog_admin_login
                check_path: paul_maxwell_blog_admin_login_check
            logout:
                path: paul_maxwell_blog_admin_logout
                target: paul_maxwell_blog_homepage

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
